PUT  http://localhost:3003/api/blogs/5e46817f0acf90352463e946
Content-Type: application/json

{
    "likes": 55,
    "title": "sdf koodia",
    "author": "jasmiina mylys",
    "url": "huuti.herokuapp.com"
}